[project]
name = "test_pytz"
version = "0.4.1"
description = "cx_Freeze script to test pytz"
dependencies = [
    "pytz",
    "setuptools<82.0",
]

[tool.cxfreeze]
executables = ["test_pytz.py"]

[tool.cxfreeze.build_exe]
include_msvcr = true
excludes = ["tkinter", "unittest"]
silent = true
